### ISSUE TITLE
Presale wallet import reports wrong balance

### ISSUE THREAD

**Issue by onepremise** [ethereum/mist#1053]
I'm unable to import my presale wallet successfully. I think something is wrong with the actual presale account. I've tried contacting info@ethereum.org and helpdesk@ethereum.org and nobody responds. I have detailed email history I've included in the email i sent to helpdesk. I'm not comfortable posting all the information here. If somebody here is aware who manages the accounts, please let them be aware. If you're aware of an issue which might prevent the balance from showing, any info is greatly appreciated.

Node logs:
[backupLogs.zip](https://github.com/ethereum/mist/files/390586/backupLogs.zip)

#### System information
``````
Version: `0.8.1`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

**Comment by luclu** [comment]
@onepremise thank you for the logs. Unfortunately your node did crash with the following error:
```
I0729 09:21:45.263746 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/jhuntley/Library/Ethereum/chaindata
I0729 09:21:47.223128 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0729 09:21:47.223148 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0729 09:21:47.223153 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0729 09:21:47.223156 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0729 09:21:47.223160 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0729 09:21:47.223446 ethdb/database.go:169] closed db:/Users/jhuntley/Library/Ethereum/chaindata
I0729 09:21:47.225917 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/jhuntley/Library/Ethereum/chaindata
I0729 09:21:47.353949 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/jhuntley/Library/Ethereum/dapp
I0729 09:21:47.356938 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0729 09:21:47.358464 eth/backend.go:201] Blockchain DB Version: 3
I0729 09:21:47.359506 core/blockchain.go:206] Last header: #1962341 [72f09d26…] TD=41966534689253451347
I0729 09:21:47.359520 core/blockchain.go:207] Last block: #1962341 [72f09d26…] TD=41966534689253451347
I0729 09:21:47.359537 core/blockchain.go:208] Fast block: #1962341 [72f09d26…] TD=41966534689253451347
I0729 09:21:47.360891 eth/handler.go:116] blockchain not empty, fast sync disabled
I0729 09:21:47.361852 p2p/server.go:313] Starting Server
I0729 09:21:47.373565 p2p/discover/udp.go:217] Listening, enode://50cae19740204aa5faae82ed697f9038ddfcc32983586dad59276992f3699e0ee3575264791dc9201e736e3f88f4a86f2edc3c11a1ac9bb320782bb5d96b5e06@[::]:30303
I0729 09:21:47.373912 p2p/server.go:556] Listening on [::]:30303
I0729 09:21:47.374510 node/node.go:296] IPC endpoint opened: /Users/jhuntley/Library/Ethereum/geth.ipc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4549541]

goroutine 891 [running]:
panic(0x4ab44c0, 0xc8200120a0)
	/Users/jeffrey/goroot16/src/runtime/panic.go:464 +0x3e6
github.com/ethereum/go-ethereum/eth/filters.(*Filter).bloomFilter(0xc822b10400, 0x0, 0xd408a333e17d60c4)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:208 +0xf1
github.com/ethereum/go-ethereum/eth/filters.(*Filter).getLogs(0xc822b10400, 0xf2ad0, 0xf2eb7, 0xc8241f0de8, 0x1, 0x1)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:137 +0x157
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc822b10400, 0xe7ef0, 0xf423f, 0x4, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:109 +0x391
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc822b10400, 0xdbba0, 0xf423f, 0x3, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc822b10400, 0x7a120, 0xf423f, 0x2, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc822b10400, 0x61a80, 0xf423f, 0x1, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc822b10400, 0x61a80, 0x1df165, 0x0, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Find(0xc822b10400, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:91 +0x1bd
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc8201500b0, 0xc822c4e990, 0x22, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/filters/api.go:534 +0xf1
reflect.Value.call(0x49cb600, 0x4bb6f48, 0x13, 0x4c07248, 0x4, 0xc822c4e9c0, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/jeffrey/goroot16/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x49cb600, 0x4bb6f48, 0x13, 0xc822c4e9c0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/jeffrey/goroot16/src/reflect/value.go:303 +0xb1
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc828ee4510, 0x5f8a3e0, 0xc82223df50, 0x5f8a210, 0xc822742eb0, 0xc822af2e70, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x1260
github.com/ethereum/go-ethereum/rpc.(*Server).execBatch(0xc828ee4510, 0x5f8a3e0, 0xc82223df50, 0x5f8a210, 0xc822742eb0, 0xc820075188, 0x1, 0x1)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/rpc/server.go:369 +0x48b
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/rpc/server.go:214 +0xc23
```
Pinging @fjl

**Comment by onepremise** [comment]
Luclu, thanks for the quick response. Let me know if there's anything further I can do to help you guys test or investigate this.

**Comment by karalabe** [comment]
I think @bas-vk already addressed this. Just got back from my holidays so I'm still a bit out of the loop :)

**Comment by bas-vk** [comment]
Correct, addressed in https://github.com/ethereum/go-ethereum/pull/2873.

**Comment by luclu** [comment]
Fixed in geth `1.4.11` which will be bundled with the upcoming release `0.8.3`.

**Comment by onepremise** [comment]
This issue still doesn't seem to be fixed. I'm still having issues importing my presale wallet. Balance is always listing 0.00 Ether. I've tried contacting Ethan from helpdesk@ethereum.org, the individual who originally was supposed to fix issues with my account and he ignores my emails. I've emailed info@ethereum.org and Ethan directly, Ethan Wilding <ethan@ethereum.org>. I think something is wrong with my presale wallet. It looks as though funds were never transferred. I've been trying to get this fixed ever since the presale ended and the main network came online. I've been very patient. I don't know what else to try. I would like access to my ether funds.

**Comment by onepremise** [comment]
This is still an issue. My presale fails to import. Nobody from the foundation responds. Ethan has left the organization and my issue was passed on to Hudson, who was responsive and looking into the issue a month ago. However, now he doesn't even respond. What is going on at the foundation? Am I being ignored on purpose? I have a valid receipt from the original exchange and all conversations documented, including the original bitcoin receipt. 

There's always this nifty exchange encouraging me to know all is good:

> Jason Huntley <onepremise@gmail.com>
> 7/31/14
> 
> to Help 
> Just checking in to see how things are coming along. Any progress on the wallet retrieval? Any info greatly appreciated.
> 
> Thanks,
> 
> Jason
> 
> 
> Help Desk <helpdesk@ethereum.org>
> 7/31/14
> 
> to me 
> We will probably be ready this weekend.  We will contact you.
> 
> 
> Jason Huntley <onepremise@gmail.com>
> 8/5/14
> 
> to Help 
> Hello,
> 
> I was just checking in to see what the status is on the wallet retrieval. Any input greatly appreciated.
> 
> Thanks,
> 
> Jason
> 
> 
> Help Desk <helpdesk@ethereum.org>
> 8/5/14
> 
> to me 
> Hi Jason.
> 
> In order to resolve the issues of people in your situation:
> 
> 1. Please go onto the sale web site and start to make a purchase by clicking "Buy Ether"
> 2. Enter an amount to purchase (it does not matter what amount), email and password.
> 3. BE SURE TO SECURELY SAVE AND BACK-UP YOUR PASSWORD. 
> 4. Download a wallet.
> 5. BE SURE TO SECURELY SAVE AND BACK-UP YOUR WALLET.
> 6. Stop and leave the sale page.  DON NOT SEND any BTC.  
> 7. Email us the wallet as an attachment from this email address. (Do not email us the password.)
> 
> We will assign your ether to the new wallet address and not assign any ether to the old wallet address.
> 
> 
> Jason Huntley <onepremise@gmail.com>
> Attachments8/5/14
> 
> to Help 
> Here's my generated wallet. Please let me know when the sale is complete. THANKS!!
> 
> Attachments area
> 
> Help Desk <helpdesk@ethereum.org>
> 8/5/14
> 
> to me 
> You are all set.
> 
> 
> Jason Huntley <onepremise@gmail.com>
> 8/5/14
> 
> to Help 
> Thanks for the quick response. One quick question for you guys. Should I be able to see my balance on the ethereum page, https://www.ethereum.org/, where it asks "If you have already purchased ether, you can check your account balance by entering your address here:"? When i enter by ethaddr it fails with "There was a problem fetching your address...".
> 
> 
> Help Desk <helpdesk@ethereum.org>
> 8/5/14
> 
> to me 
> Because of your special situation that won't work for you.
