### ISSUE TITLE
wallet 0.3.8 crash

### ISSUE THREAD

**Issue by ricardiinhu** [ethereum/mist#117]
hi when i access the wallet, it just crashes and close the app... do you have an idea of what´s happening? i´m using windows.
if is necessary more information, ask me!

**Comment by frozeman** [comment]
Windows seems to be problematic, we will look into this.

**Comment by ricardiinhu** [comment]
Ok! I wanna say that this start to happen after I send some ether from the account I created to the wallet I created.. Before doing that, the app was working good.

**Comment by atonra7** [comment]
When the transaction is completed, after a while everything starts to work again.

**Comment by ricardiinhu** [comment]
atonra7 you were right, i tried to open today and it worked again... maybe it´s a litle bug,

**Comment by crioux** [comment]
Also having this problem.

**Comment by jonpspitz** [comment]
This is happening to me on OSX. Frustrating.

**Comment by thehalfsoul** [comment]
Same is happening to me. Hopefully it works tomorrow or the next day. Thanks

**Comment by frozeman** [comment]
Sorry for the inconvenience, the best option right now is to use an older version https://github.com/ethereum/mist/releases/tag/0.3.7

I'm looking into this issue. I have the cause, but not a fix yet :(

**Comment by thehalfsoul** [comment]
Ok that's great thanks.

**Comment by frozeman** [comment]
Please try this version and let me know if it fixes your issues.
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0 (my drop box, so might appear later, currently uploading)

**Comment by Codnova** [comment]
I also encountered this problem, i'm using Win 10 x64 (1511 [Build 10586.63])  Mist opened fine, synced up, i created the account Etherebase and two wallets from that account, after i send the first TX from account to wallet, the Mist crashed, every time i open it Mist crashes.

**Comment by frozeman** [comment]
@Codnova can you please try the version linked above?

**Comment by wappinghigh** [comment]
The linked version you have there posted in your dropbox "0.3.9pre" is the last one I tried. It is now hanging again "Starting Ethereum Node"... Is this just supposed to run out of the box, or should something else be installed? :) I am using OSX.. :)

**Comment by frozeman** [comment]
No the previous ones don't overwrite each other, except they use the same datatdir in `~/Library/App ..Support/Mist`

I guess your issue is a different one: Please see https://github.com/ethereum/mist/issues/65

**Comment by ricardiinhu** [comment]
hi frozeman, sorry for the delay on answer.. i´m installing on another computer the wallet of your dropbox, but the sync is veeeeery slow... what can it be?

**Comment by frozeman** [comment]
Less peers? its on the end  a 3gb blockchain...

**Comment by jonpspitz** [comment]
I dowloaded the new version and it now just takes longer before it doesn't open. I'm not a programmer by any means, I really just want to buy ether. Have been wanting to buy for a while. I'm told this is the only way? Help.

**Comment by wappinghigh** [comment]
So it is fixed? or not?

**Comment by frozeman** [comment]
The random crash is fixed. The crash on the start probably not.
@jonpspitz can you please provide the log files in your mist data folder: `%APPDATA%\Roaming\Mist`

**Comment by ricardiinhu** [comment]
hi frozeman! i guess you already know, but the bug is fixed! i transfer some ether from the account to the wallet and the app didn´t crash.
thank you

**Comment by rafajafar** [comment]
I have this problem on 0.3.8 as well. It was fine for a week until I added a wallet and deposited eth into it. Now it crashed every time I load up the program. Tried restarting the computer, no fix. Running as administrator, no fix. Any other things I can try?

**Comment by jonpspitz** [comment]
Still doesn't work for me.
ᐧ

Best,

*Jon P Spitz*
Tel: 1+585-613-6168
jonpspitz@gmail.com
<http://www.linkedin.com/in/jonpspitz>  <http://twitter.com/jonpspitz>

**Comment by rafajafar** [comment]
Added log found in: \AppData\Roaming\Mist\IndexedDB\file__0.indexeddb.leveldb

I didn't see any other log file anywhere... except the old log which read exactly the same as that one.

**Comment by rafajafar** [comment]
The moment it displays peer data at the top of the application when it first loads, the application crashes.

**Comment by ricardiinhu** [comment]
rafajafar, try the version that frozeman showed, and see if works:
"frozeman commented 8 days ago:
Please try this version and let me know if it fixes your issues.
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0 (my drop box, so might appear later, currently uploading)"

**Comment by rafajafar** [comment]
Sure do you know how I can upgrade safely? Just replace the Ethereum-Wallet app?

**Comment by frozeman** [comment]
The [latest release](https://github.com/ethereum/mist/releases/tag/0.3.9) should fix that and also contains logs

**Comment by thehalfsoul** [comment]
I can confirm the latest version that Fabian sent 0.3.9 works great for me :)

**Comment by rafajafar** [comment]
Yes. I didn't realize there was a new version. It's all fixed. Thanks, fellas!
