### ISSUE TITLE
Multisig creation stuck at 'checking for contract receipt'

### ISSUE THREAD

**Issue by chtmorris** [ethereum/mist#1370]
![screen shot 2016-11-01 at 2 26 25 pm](https://cloud.githubusercontent.com/assets/5326519/19881317/8c84197c-a03f-11e6-9474-643a48b4f4a0.png)

Stuck here for 3 days.  Gas submitted may have been below amount required.

v0.8.7, OSX 10.12, geth

**Comment by luclu** [comment]
@chtmorris this might be caused by the currently [lowered gas limit](http://ethstats.net/). Unfortunately there might be no workaround but to wait for the [2nd HF post attack](https://www.reddit.com/r/ethereum/comments/5afory/update_hard_fork_block_number_delay_10312016/). 

Although the current contract wallet will only use 1.962.239 gas (1st HF)(https://blog.ethereum.org/2016/10/18/faq-upcoming-ethereum-hard-fork/), it seems that the supplied gas (3.000.000) will be counted, thus the transaction rejected.

Duplicate of https://github.com/ethereum/mist/issues/1335.

**Comment by luclu** [comment]
Issue should be resolved on main-net.

**Comment by chtmorris** [comment]
@luclu I'm on the main-net with updated geth and Ethereum Wallet and this wallet is still hanging.  Is there a way I can just remove it from my Library data?
