### ISSUE TITLE
"eth" node crash on 0.5.0 mist

### ISSUE THREAD

**Issue by dobcrypto** [ethereum/mist#231]
![glgnz2k 1](https://cloud.githubusercontent.com/assets/16653151/13501973/e4675710-e179-11e5-9913-43732c8da4a5.png)

**Comment by dobcrypto** [comment]
Hm, after download the [latest stable binary](https://build.ethdev.com/builds/Windows%20Go%20master%20branch/Geth-Win64-latest.zip)and run it, all is good.
![j81hrfc 1](https://cloud.githubusercontent.com/assets/16653151/13505661/1bc99932-e18b-11e5-9776-387edf49886e.png)

**Comment by frozeman** [comment]
Yes `eth` is a bit unstable for now, i couldn't fully test the windows build.
We are working on bringing eth back to stable.

notifing @chriseth

**Comment by chriseth** [comment]
We fixed some issues recently. Do you have more information about the crash? If not, I think this can be closed.

**Comment by frozeman** [comment]
@chriseth this happened in the latest release, so its the windows binary we've build yesterday. I guess its that opencl.dll issue

**Comment by dobcrypto** [comment]
@chriseth @frozeman  
No, the problem is still there.

1. I need "eth node" wallet in "Mist Wallet 0.5.0 (Beta 8)". 
Even after the synchronization of the "geth" blocks, I can not choose the node in wallet =(
![fc1xrss 1](https://cloud.githubusercontent.com/assets/16653151/13531757/410c5d2a-e239-11e5-9e2a-62bdc0e9d809.png)

2. Mist Wallet 0.5.0 (Beta 8) does not start until I manually launch in the console(cmd) "geth.exe"
![xxk6xx7 1](https://cloud.githubusercontent.com/assets/16653151/13531842/a636be84-e239-11e5-89cf-df556f3267b1.png)
It is not comfortable.

**Comment by oldpoison** [comment]
I have the same problem, I Need "Eth" ethereum node.. because my wallet is there... but not working... not synchronization.. need some help

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
