### ISSUE TITLE
0 of 12 confirmations, unable to send ETH

### ISSUE THREAD

**Issue by ChesterBro** [ethereum/mist#3397]
I'm having some issue where I send eth but it's not confirming. It just sits there grayed out. I ensured that I have enough gas. And using the latest wallet version.

Ive tried several things to troubleshoot. Deleted eth wallet folder which seem to remove the prior transaction. I tried deleting the whole block chain and resyncing it (done this several times). I tried sending it to different addresses. I tried waiting a couple days without sending any eth in hopes any previous transactions just fails or times out. I'm all out of ideas.

Can anyone please help or share a solution if experienced the same thing?

Thanks in advanced

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,699,793
```

**Comment by ermito** [comment]
same at me.
Console output:
`ipcProviderBackend - Send request failed TypeError: Cannot read property 'contractAddress' of null`

**Comment by unknown1235** [comment]
Make sure you give higher gas prices.  Check online at ether gas station to see how much gas you should be spending.

Make sure your fully synced.
During my syncing process, once it got to like 95%, it stops downloading new blocks.  
I think its importing the states from the blocks or something.  This process will take hours and it will seem like its not doing anything but its actually importing states in the background.  
Wish they give some kind of progression bar or some indicator about it.  Most people would think its frozen up or not working.
Anyway after several hours it will begin downloading the remaining blocks or something.

**Comment by fgaspar** [comment]
Hello,

I have this exact problem, I've tried both having the full block chain synced and I've also tried with the light version (light client). I've tried a range of different gas prices, but my transactions are never listed on https://etherscan.io/, so I doubt they are leaving my PC. I'm not sure how to check the console output, but it looks like nothing goes out. The weirdest thing is that about 2 weeks ago I managed to transfer funds, now I can't and I don't believe I did anything to ruin that.

I've been trying with the light network, and as far as I know it is synced (block numbers match), the only thing I've noticed is that I either have 0 or 1 peers, it's very rare to have more and they don't last for long.

**Comment by ChesterBro** [comment]
@fgaspar yes exactly the same issue im having.  I even formatted my laptop thinking it may be some kind of file corrupted somehow but still having the same issue.  

Does the light network give you any confirmations?

**Comment by fgaspar** [comment]
@ChesterBro, no, no confirmations, it's just faster to sync (and smaller) so I've switched to it for faster experiments

**Comment by juliotec** [comment]
I have the same problem, i have 100% of the blocks, 1 peer sending me more blocks, send the transactions with all the fees posible and i cant sent any eth, stay in 0 confirmations for many time, i think that is a wallt bug, i have 

Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,699,793

**Comment by DeepBlueFoundation** [comment]
I have the same problem with mist in ropsten too.

**Comment by fgaspar** [comment]
I just "solved this" by trying to move the ETH from another internet connection. Worked on the first try.

I did it by just running ethereum-wallet, on the previous location I even tried manually opening the correct router ports with no success and connecting with a VPN to the place where I was able to do the transfer.

I was having issues with Virgin Media (UK).

**Comment by falehenrique** [comment]
I @evertonfraga has this error been fixed?

> 
[ERROR] ipcProviderBackend - Send request failed TypeError: Cannot read property 'contractAddress' of null
> 

I am using the Ethereum Wallet with geth 1.7.0, I had the same error with 1.7.2.

Tks.

**Comment by evertonfraga** [comment]
@falehenrique yes, it was solved and will be released on 0.9.4, probably next week.

https://github.com/ethereum/mist/pull/3340

**Comment by rgolev** [comment]
Hi!

No, error not fixed


>Четверг, 25 января 2018, 19:23 +05:00 от Henrique <notifications@github.com>:
>
>I  @evertonfraga has this error been fixed?
>[ERROR] ipcProviderBackend - Send request failed TypeError: Cannot read property 'contractAddress' of null
>I am using the Ethereum Wallet with geth 1.7.0, I had the same error with 1.7.2.
>Tks.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


________________________
С уважением, Голев Роман
Сот. тел. 89027989831
E-mail: rgolev@mail.ru
ICQ: 202536883

**Comment by n1tr0k** [comment]
Hi all, 
I have to transfer only a single ethereum to Bitstamp but I obtain a stuck transaction with "0 of 12 confirmations" also after 8-12h of synchronization (Eth Wall 0.9.3 and geth 1.6.7). From etherscan results transaction failed with an "out of gas" reason and Gas Used By Txn: 21001 . I've already applied the max fee possible from the GUI. Any solution? Sry but I'm newbe on the matter...
Tks

**Comment by n1tr0k** [comment]
I @evertonfraga some news about the 0.9.4?
I've 3 transactions pending with "0 confirmations" from 7 days.
Thanks in advance

**Comment by fcaldas** [comment]
@n1tr0k a temporary fix is to remove the ~/.config/Ethereum Wallet folder, this will erase all pending transactions.

**Comment by evertonfraga** [comment]
The release took longer than expected, but it is now fixed and available for update.

**Comment by R-T-Code** [comment]
THIS WORKS.

Hey i did try to send my eth from mist wallet to other wallet and it lasted 10h with 0 out of 12 confirmation. After hours of searching and testing i download MetaMask extension on chrome, uploaded my mist wallet keys on it and made the transaction from there. 30min later my transaction was done. Mist wallet to the bin

Good luck everyone
