### ISSUE TITLE
Incorrect detection of Network Time Usage and Blank Screen on Loading/In Wallet

### ISSUE THREAD

**Issue by eyecikjou567** [ethereum/mist#466]
Node type: geth/eth
OS: windows 10 x64
Network type: main/test
Mist version: 0.6.0 (Beta 11)

After startup the loading screen remains blank. Initially, Mist got into the wallet, changing between eth and geth did not change anything, changing between main/test on either did not change anything.

Tried workarounds for this behaviour; deleting all mist related content in the executable folder and redeploying it.

Additionally, my time settings are detected incorrectly on Windows 10 x64 using 0.de.pool.ntp.org despite having sync'd it not seconds beforehand.

Tried workarounds for this behaviour; Temporarily changing time server, disabling time server, reenabling time server, syncing manually with time server

![The mentioned Time Error](https://i.imgur.com/Oos9yzx.png)

```
I0404 20:34:52.395965   10348 database.go:71] Alloted 433MB cache to C:\Users\Tim\AppData\Roaming\Ethereum\chaindata
I0404 20:34:52.486993   10348 database.go:71] Alloted 78MB cache to C:\Users\Tim\AppData\Roaming\Ethereum\dapp
I0404 20:34:52.511001   10348 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0404 20:34:52.511001   10348 backend.go:362] Blockchain DB Version: 3
I0404 20:34:52.513001   10348 blockchain.go:214] Last header: #1276444 [acf54cdf…] TD=12059428946170426077
I0404 20:34:52.513001   10348 blockchain.go:215] Last block: #1276444 [acf54cdf…] TD=12059428946170426077
I0404 20:34:52.513001   10348 blockchain.go:216] Fast block: #1276444 [acf54cdf…] TD=12059428946170426077
I0404 20:34:52.513001   10348 handler.go:92] blockchain not empty, fast sync disabled
I0404 20:34:52.518002   10348 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0404 20:34:52.518002   10348 server.go:311] Starting Server
I0404 20:34:54.554162   10348 udp.go:212] Listening, enode://a0a87e4c797e919bfec235f1fd5c4fb0b59503513b1417e4dbb1659ae8d8ff60b7628e4244b280a4b11508936c80eed2bbf92dd3eb115eb9425f6c5fdccc614f@[::]:30303
I0404 20:34:54.554162   10348 backend.go:526] Server started
I0404 20:34:54.554162   10348 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0404 20:34:54.557163   10348 server.go:552] Listening on [::]:30303
I0404 20:35:14.560168   10348 downloader.go:288] Block synchronisation started
I0404 20:36:24.836838   10348 blockchain.go:1251] imported 7 block(s) (0 queued 0 ignored) including 49 txs in 2.0096009s. #1276451 [c48a60b2 / 89d649d4]
I0404 20:36:25.049902   10348 blockchain.go:1251] imported 7 block(s) (0 queued 0 ignored) including 13 txs in 213.0638ms. #1276458 [a7a61f0a / 45a30dbd]
I0404 20:36:27.704142   10348 blockchain.go:1251] imported 6 block(s) (0 queued 0 ignored) including 25 txs in 508.595ms. #1276464 [f6069fb3 / 2b341177]
I0404 20:36:28.894829   10348 blockchain.go:1251] imported 2 block(s) (0 queued 0 ignored) including 9 txs in 104.0416ms. #1276466 [9f51495c / 74355463]
I0404 20:36:32.819892   10348 blockchain.go:1251] imported 10 block(s) (0 queued 0 ignored) including 36 txs in 787.2353ms. #1276476 [43eec7bb / 5d9c4b91]
I0404 20:36:33.288031   10348 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 24.0082ms. #1276477 [7b2601e4 / 7b2601e4]
I0404 20:36:34.028253   10348 blockchain.go:1251] imported 6 block(s) (0 queued 0 ignored) including 30 txs in 160.0491ms. #1276483 [ae495e6a / e472e620]
I0404 20:36:36.311935   10348 blockchain.go:1251] imported 9 block(s) (0 queued 0 ignored) including 14 txs in 833.2491ms. #1276492 [a4c6c59f / 82f25b92]
I0404 20:36:47.799261   10348 blockchain.go:1251] imported 2 block(s) (0 queued 0 ignored) including 0 txs in 22.0069ms. #1276494 [5d3ffa91 / 14da6dbf]
I0404 20:36:48.700530   10348 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 13.0039ms. #1276495 [38cd4b01 / 38cd4b01]
I0404 20:36:54.626304   10348 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 9.0027ms. #1276496 [563a2e6f / 563a2e6f]
I0404 20:36:58.142358   10348 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 9.0039ms. #1276497 [a9a6a340 / a9a6a340]
```

Console output:
```
file:///C:/Users/<username>/ethereum/resources/interface/wallet/de099c7891b1fc43945261e5a9c630231e1ed0ad.js Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:7 Uncaught ReferenceError: Meteor is not defined
```

**Comment by luclu** [comment]
@eyecikjou567 could you please try the latest version 0.7.2 [link](https://github.com/ethereum/mist/releases). This should fix the time-sync issue.

Regarding the blank window please look here: https://github.com/ethereum/mist/issues/599

Hope that helps!

**Comment by eyecikjou567** [comment]
The Time Sync issue is still there. ![The message persists](http://i.imgur.com/N4sTtiJ.png)

The blank windows issue is mostly fixed in the new version, it shows a blank window for a really short amount of time with or without the fix from #599

**Comment by luclu** [comment]
@eyecikjou567 how is geth 1.4.4 (bundled with version 0.7.4) behaving for you?

**Comment by eyecikjou567** [comment]
Issue unchanged.

Performance is better tho.

**Comment by luclu** [comment]
Could you please give me the output of:
```
reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time
```
See https://github.com/ethereum/mist/issues/397 for context.

**Comment by eyecikjou567** [comment]
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time
    ErrorControl    REG_DWORD    0x1
    ImagePath    REG_EXPAND_SZ    %SystemRoot%\system32\svchost.exe -k LocalService
    Type    REG_DWORD    0x20
    Description    REG_SZ    @%SystemRoot%\system32\w32time.dll,-201
    ObjectName    REG_SZ    NT AUTHORITY\LocalService
    ServiceSidType    REG_DWORD    0x1
    RequiredPrivileges    REG_MULTI_SZ    SeAuditPrivilege\0SeChangeNotifyPrivilege\0SeCreateGlobalPrivilege\0SeSystemTimePrivilege
    FailureActions    REG_BINARY    80510100000000000000000003000000140000000100000060EA000001000000C0D401000000000000000000
    Start    REG_DWORD    0x2
    DisplayName    REG_SZ    Windows Time

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Config
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\SecureTimeLimits
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Security
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TriggerInfo
```

Edited Start to 0x3 and now the Wallet is behaving correctly. Issue can be closed, many thanks!

**Comment by luclu** [comment]
Good to hear. I will link this to https://github.com/ethereum/mist/issues/397 for context.
