### ISSUE TITLE
Wrong "Your computer's clock is not synced." error prevents Mist from launching

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#583]
Node type: geth
OS: archlinux, kernel 4.5.1, systemd 229
Network type: main
Mist version: 0.7.2.r1.g80ec64f-1

as you can see in the screenshot i get the error `Your computer's clock is not synced.`

![screenshot at 2016-05-09 14 50 27](https://cloud.githubusercontent.com/assets/15729797/15113655/dcbb4d7c-15f5-11e6-9ac7-a7d3d0319a97.png)

But you can also see my clock is working correctly.

Also, I very well have `ntpd` running:

```
 ~ $ uname -a
Linux 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux
 ~ $ pacaur -Q mist-git
mist-git 0.7.2.r1.g80ec64f-1
 ~ $ systemctl status ntpd
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-05-09 14:06:40 CEST; 45min ago
  Process: 786 ExecStart=/usr/bin/ntpd -g -u ntp:ntp (code=exited, status=0/SUCCESS)
 Main PID: 827 (ntpd)
    Tasks: 2 (limit: 512)
   CGroup: /system.slice/ntpd.service
           └─827 /usr/bin/ntpd -g -u ntp:ntp
```

Maybe it does not recognize services run by `systemd`?

Also, `apt-get` is very Ubuntu specific.

Finally, how to bypass this error? I see this was introduced to fix all that node-wont-sync issues. However, I'm currently unable to run mist because it stops working and I cant click this window away.

**Comment by Denton-L** [comment]
I am currently running Mist on Arch, myself, and it works just fine. I was using the mist package instead of the mist-git package on the AUR, however.

Try running `geth` in your terminal and see what it says. Geth is the backend for Mist which is responsible for syncing the blocks.

**Comment by 5chdn** [comment]
geth just syncs the blockchain normally. it must be a message from mist.

**Comment by jdacal** [comment]
I have this exact same issue on Windows 10.  Time is properly synched.  Wallet shows invalid date.

**Comment by megahz2** [comment]
Same here with windows 8.1. 
1. "invalid date since last block"..
2. not downloading blocks and showing 0 block number.  once in a while seconds indicator ticks for a bit, butt still not downloading blocks..
3. In the mist log it shows last block downloaded is 1488804 no errors..

Time on PC is all good. and looks like fluctuating 10 to 11 12 connected other nodes. 
I also tried to launched geth waited for block update and then launch mist and there was no difference. 
antivirus does not appear to be interfering, i have mist running on other PCs ok with same antivirus..

note: not sure if its an issue or related, but I sent 3eth to dao to get tokens, I see I received Tokens in watched tokens, but I noticed the transaction shows 0 of 12 confirmations.. 

It seems to be since I transferred eth to get dao tokens, watching DAO contract and holding/watching DAO Tokens.


![20160510_004000](https://cloud.githubusercontent.com/assets/6596253/15136556/1e11b160-1648-11e6-9ef0-a8e4995df835.jpg)
![20160510_003948](https://cloud.githubusercontent.com/assets/6596253/15136565/2d99a228-1648-11e6-9662-b9876fa4b146.jpg)

**Comment by 5chdn** [comment]
yes this is a mist issue and not related to geth / eth. the nodes in the background just work fine.

**Comment by luclu** [comment]
@5chdn I just tested on a simple arch installation with i3 and can confirm. Will look into it hopefully soon.

**Comment by bartobri** [comment]
Same issue for me on arch linux 4.5.4. ntpd is installed and running. Getting error dialog box: "Your computer's clock is not synced.". I can not get past the mist splash screen.

**Comment by luclu** [comment]
Seems to be related to **timedatectl** not recognizing **ntpd's** sync status.

Mist uses the npm-module [os-timesync](https://github.com/fjl/os-timesync) ([line](https://github.com/ethereum/mist/blob/6c59a98e94ed2d688dfdd1604fb9eff4cd90732a/main.js#L14))

This will check with **systemd**'s `timedatectl status` and matches its output:
`var match = /^\s*(NTP enabled|Network time on): (yes|no)\s*$/mi.exec(stdout);`

**timedatectl** does not recognize **ntpd** [installed](https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon) and running as it outputs on Arch:
```
Network timeon: no
NTP synchronized: no
```
to be continued...

**Comment by luclu** [comment]
aha, it takes some time to pick up it up and reflect on this:
```
Network time on: no
NTP synchronized: yes
```
I will send a PR to [os-timesync](https://github.com/fjl/os-timesync).

**Comment by 5chdn** [comment]
sweet

**Comment by luclu** [comment]
PR: https://github.com/fjl/os-timesync/pull/4

**Comment by luclu** [comment]
@5chdn could you please give me the output of `timedatectl`?
Then issue `timedatectl set-ntp true` and check the output again?

**Comment by 5chdn** [comment]
0 ✓ user@hoster ~ $ timedatectl
          Local time: Mon 2016-06-13 19:32:06 CEST
      Universal time: Mon 2016-06-13 17:32:06 UTC
            RTC time: Mon 2016-06-13 17:32:06
           Time zone: Europe/Berlin (CEST, +0200)
     Network time on: yes
    NTP synchronized: yes
     RTC in local TZ: no
    0 ✓ user@hoster ~ $ timedatectl set-ntp true
    0 ✓ user@hoster ~ $ timedatectl
          Local time: Mon 2016-06-13 19:32:39 CEST
      Universal time: Mon 2016-06-13 17:32:39 UTC
            RTC time: Mon 2016-06-13 17:32:39
           Time zone: Europe/Berlin (CEST, +0200)
     Network time on: yes
    NTP synchronized: yes
     RTC in local TZ: no

**Comment by luclu** [comment]
Version 0.7.5 was released including several changes to os-timesync. Please check if this solves this issue for you @Denton-L @bartobri @5chdn.

**Comment by bartobri** [comment]
@luclu 

Downloaded Ethereum-Wallet-linux64-0-7-5.zip, unzipped, and ran 'Ethereum-Wallet'. No good. Still get the same error.

Let me know if I am doing something wrong. There doesn't seem to be any installation procedure, so I assume all I need to do is run the 'Ethereum-Wallet' binary.

**Comment by luclu** [comment]
@bartobri could you please give me the output of `timedatectl`?
It seems our packaging omitted the `npm update` and is still on os-timesync `1.0.5` :/

**Comment by bartobri** [comment]
@luclu 
```
$ timedatectl
      Local time: Thu 2016-06-16 11:41:20 EDT
  Universal time: Thu 2016-06-16 15:41:20 UTC
        RTC time: Thu 2016-06-16 15:41:20
       Time zone: US/Eastern (EDT, -0400)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by 5chdn** [comment]
@bartobri type `timedatectl set-ntp true` and try again. this worked for me.

@luclu the issue remains, however enabling network time fixes it for me:

    1 ✗ user@hoster ~ $ timedatectl 
          Local time: Fri 2016-06-17 09:57:41 CEST
      Universal time: Fri 2016-06-17 07:57:41 UTC
            RTC time: Fri 2016-06-17 07:57:42
           Time zone: Europe/Amsterdam (CEST, +0200)
     Network time on: no
    NTP synchronized: yes
     RTC in local TZ: no
    0 ✓ user@hoster ~ $ timedatectl set-ntp true
    0 ✓ user@hoster ~ $ timedatectl 
          Local time: Fri 2016-06-17 09:58:02 CEST
      Universal time: Fri 2016-06-17 07:58:02 UTC
            RTC time: Fri 2016-06-17 07:58:02
           Time zone: Europe/Amsterdam (CEST, +0200)
     Network time on: yes
    NTP synchronized: yes
     RTC in local TZ: no

Is the mist browser checking for network time or ntp synchronization? And what's the difference anyways?

**Comment by luclu** [comment]
Unfortunately the updates didn't make it in this release. 
Starting with our next release we are hopefully using travisCI to package the binaries.

---

Supposedly `Network time on:` indicates NTP to be enabled,
and `NTP synchronized:` that the OS is in sync through NTP.

In reality the output is inconsistent on different OS:
 - Ubuntu only gives a `yes` for the first entry
 - whereas Arch only for the later one

**Comment by bartobri** [comment]
@5chdn That worked! Thanks!

**Comment by luclu** [comment]
Unfortunately `1.0.6` did make it into `0.7.5`/`0.7.6` due to some problems with our packaging workflow. This has been resolved now - version `0.8` is scheduled for the 5th of July.

**Comment by luclu** [comment]
Do you still encounter this with version `1.0.6` of os-timesync shipped with `0.8.0` and `0.8.1`?

**Comment by rehno-lindeque** [comment]
I'm still having this issue still with `0.8.1` and more recently with `0.8.2` on NixOS.

```
$ timedatectl status
      Local time: Fri 2016-08-26 06:04:57 UTC
  Universal time: Fri 2016-08-26 06:04:57 UTC
        RTC time: Thu 2016-08-25 22:30:13
       Time zone: n/a (UTC, +0000)
 Network time on: n/a
NTP synchronized: yes
 RTC in local TZ: no
```

One thing I notice is that os-timesync does not parse for `n/a`: https://github.com/fjl/os-timesync/pull/3/files#diff-168726dbe96b3ce427e7fedce31bb0bcR45

---

Additional info:

```
$ systemctl status ntpd
● ntpd.service - NTP Daemon
   Loaded: loaded (/nix/store/8mnpj80vcmcl2145ykvprzan5wjixb29-unit-ntpd.service/ntpd.service; bad; vendor preset: enabled)
   Active: active (running) since Fri 2016-08-26 06:02:59 UTC; 2min 15s ago
  Process: 9864 ExecStart=ntpd -g -c /nix/store/r2yjzazvdsgcpqgy2w730nw4fqqc0r35-ntp.conf -u ntp:nogroup (code=exited, status=0/SUCCESS)
  Process: 9857 ExecStartPre=/nix/store/d135dbbjwzxdv0kxnlbwq09sxb2gadqf-unit-script/bin/ntpd-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 9867 (ntpd)
   CGroup: /system.slice/ntpd.service
           └─9867 ntpd -g -c /nix/store/r2yjzazvdsgcpqgy2w730nw4fqqc0r35-ntp.conf -u ntp:nogroup

Aug 26 06:02:59 virtualbox2015 systemd[1]: Starting NTP Daemon...
Aug 26 06:02:59 virtualbox2015 systemd[1]: Started NTP Daemon.
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: proto: precision = 0.056 usec (-24)
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen and drop on 0 v6wildcard [::]:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen normally on 2 lo 127.0.0.1:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen normally on 3 enp0s3 10.0.2.15:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen normally on 4 lo [::1]:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listen normally on 5 enp0s3 [fe80::a00:27ff:fe8f:f47c%2]:123
Aug 26 06:02:59 virtualbox2015 ntpd[9867]: Listening on routing socket on fd #22 for interface updates
```

```
$ cat /nix/store/r2yjzazvdsgcpqgy2w730nw4fqqc0r35-ntp.conf
driftfile /var/lib/ntp/ntp.drift

restrict 127.0.0.1
restrict -6 ::1

server 0.nixos.pool.ntp.org iburst
 server 1.nixos.pool.ntp.org iburst
 server 2.nixos.pool.ntp.org iburst
 server 3.nixos.pool.ntp.org iburst
```

**Comment by luclu** [comment]
@rehno-lindeque what does `ps -A -o command | grep ntpd` output?

**Comment by rehno-lindeque** [comment]
@luclu 

```
$ ps -A -o command | grep ntpd
ntpd -g -c /nix/store/r2yjzazvdsgcpqgy2w730nw4fqqc0r35-ntp.conf -u ntp:nogroup
grep ntpd
```

**Comment by luclu** [comment]
Thank you @rehno-lindeque 

@fjl we might want to check for `NTP synchronized: yes`? I don't recall, but I think you mentioned a reason not to do so.

**Comment by fjl** [comment]
The reason was that the clock is not always synchronized even though NTP is enabled (i.e. the user has just turned on ntp and it's not done yet). There should be no error in this case.

> One thing I notice is that os-timesync does not parse for n/a

I can fix it to return an error in this case. That should prevent the popup because mist does nothing if checking for the time sync fails.

**Comment by luclu** [comment]
Ah cool, so let's check for `NTP synchronized` instead of `NTP enabled`. 

For example timedatectl does not recognize Chrony's systemd service file, but will report the correct `NTP synchronized` state. Also overriding the time (in a session) will be reflected as a correct `NTP synchronized` flag, but will leave `NTP enabled` as yes.
